apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sev

---

apiVersion: v1
kind: Secret
metadata:
  name: my-sev-token
  annotations: 
    kubkubernetes.io/service-account.name: my-sev
  type: kubernetes.io/service-account-token


