apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sev

---

apiVersion: v1
kind: Secret
metadata:
  name: my-sev-token
  annotations: 
    kubernetes.io/service-account.name: "my-sev"
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list"]


